on:
  push:
    branches:
      - master
     
name: Terraform Apply

jobs:
        
  TfApply:
    name: TfApply
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.REGION }}

    - name: Terraform plan
      shell: pwsh
      run: |
        cd modules/network
        terraform init -backend-config="./tfvars/terraform_state.tfvars"
        terraform plan -var-file="./tfvars/terraform.tfvars"
        
    - name: Terraform apply
      shell: pwsh
      run: |
        cd modules/network
        terraform apply -auto-approve -var-file="./tfvars/terraform.tfvars" 